### ISSUE TITLE
Media findOne() Using Cosmic ID returns 404

### ISSUE THREAD

**Issue by pcwa-ahendricks** [cosmicjs/cosmic-sdk-js#26]
I'm able to query single media objects using the following syntax:

```javascript
const post = await cosmic.media
  .findOne({
     name: '1234NAME.jpg'
  })

const post = await cosmic.media
  .findOne({
     original_name: 'NAME.jpg'
  })
```

and so on.. but, I'm unable to use "id" as a param, for example, the following returns a 404 when I use a valid/present ID

```javascript
const post = await cosmic.media
  .findOne({
     id: 'SOME_ID'
  })
```

**Comment by tonyspiro** [comment]
Thanks for the report. We are looking into this.

**Comment by pcwa-ahendricks** [comment]
Actually, I'm unable to query using id with curl as well (ex. below returns 404), so maybe this isn't directly related to the @cosmicjs/sdk package.

```shell
curl https://api.cosmicjs.com/v3/buckets/BUCKET_NAME/media \
    -d read_key=READ_KEY \
    --data-urlencode query='{"id":"64f0b2cd513ef413daf6bee7"}' \
    -d props=id,name,imgix_url,metadata \
    -G
```

**Comment by jazibsawar** [comment]
@pcwa-ahendricks pushed fixes to the API. Can you check if that resolves your issue?

**Comment by pcwa-ahendricks** [comment]
@jazibsawar Still getting {"status":404,"message":"No media found in bucket 'BUCKET_NAME'"}% when using curl

**Comment by jazibsawar** [comment]
@pcwa-ahendricks can you please contact support so we look into the issue?

**Comment by tonyspiro** [comment]
@pcwa-ahendricks this should now be fixed. Please test and let me know if there are any issues. I'll go ahead and close this.
