### ISSUE TITLE
Cosmic JS SDK media.inserOne returns empty media array

### ISSUE THREAD

**Issue by mrdja026** [cosmicjs/cosmic-sdk-js#32]
Hiya folks,

Found that in this example the response to the await `cosmic.media.insertOne` returns object with an empty array of media

![image](https://github.com/cosmicjs/cosmic-sdk-js/assets/15103310/52e5df96-afbe-4681-872c-a1f4900d7869)

Tried it with my Astro project
Package version 1.0.5

Stakblizz to the issue https://stackblitz.com/edit/cosmic-react-drozone-example-7wjwqq?file=pages%2Findex.js,package.json

Tried in my project also

**Comment by StacyFranco** [comment]
I'm having the same problem in the versions 1.0.10 and 1.0.9

**Comment by tonyspiro** [comment]
@mrdja026 and @StacyFranco thanks for the report. We'll take a look.

**Comment by tonyspiro** [comment]
@mrdja026 Can you try again on this link? https://stackblitz.com/edit/cosmic-react-drozone-example?file=pages%2Findex.js

**Comment by mrdja026** [comment]
@tonyspiro still the same result, picture is uploaded to my bucket, but the response is empty

<img width="444" alt="Screenshot 2023-11-22 at 08 53 24" src="https://github.com/cosmicjs/cosmic-sdk-js/assets/15103310/208c2e26-b6f0-43da-b85f-16bafaa2e6e9">

**Comment by jazibsawar** [comment]
@mrdja026 can you please share your bucket slug and the image you're trying to upload? In my testing, I couldn't able to reproduce this error.

**Comment by StacyFranco** [comment]
@jazibsawar I have the same issue I'm using this bucket slug: portfolios-dev-d9ef6e50-8881-11ee-b1e6-859100b5370c
the project I'm using  the application can be looked at : 
https://github.com/StacyFranco/portfolio-node-nextjs
when I do the media.insertOne continue to come an empty array.

**Comment by StacyFranco** [comment]
thanks it's working again for me!

**Comment by mrdja026** [comment]
@jazibsawar hi, sure
slug: mrdjanacme-development
![740130_20220522123558_1](https://github.com/cosmicjs/cosmic-sdk-js/assets/15103310/7157a901-cd68-48c9-b56b-e5ace5ae20be)
this is the picture

**Comment by mrdja026** [comment]
Can confirm that it is working now after upgrading to 1.0.10, is there maybe a chance to provide an example without dropzone, since when I try creating without the lib, don't want to use React 

I used the example on from the [docs ](https://www.cosmicjs.com/docs/api/media#create-media) without the third-party lib

```
const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) {
      setFile(e.target.files[0])
    }
  }

  const handleUpload = async () => {
    if (file) {
      console.log("DEBUG_FILE", { file })
      const { name } = file
      const blob = new Blob([file], { type: file.type })
      const media = { originalname: name, buffer: blob }
      const data = await sendMedia(media)
      console.log("DEBUG_UPloaded data", data)
    }
  }
```
Creating file to blob, because if I don't do that, it throws an error where it says that the parameter 2 should be a blob

![image](https://github.com/cosmicjs/cosmic-sdk-js/assets/15103310/782785e4-535e-437e-9599-27532dc40d85)

**Comment by jazibsawar** [comment]
@mrdja026 It is good to know that it works for you. 

> is there maybe a chance to provide an example without dropzone

Will look into it.

**Comment by tonyspiro** [comment]
Closing this as it seems that the issue has been resolved.
