### ISSUE TITLE
Use a spec-compliant FormData polyfill or drop node <18

### ISSUE THREAD

**Issue by KaelWD** [cosmicjs/cosmic-sdk-js#35]
form-data does not support File objects https://github.com/form-data/form-data/issues/124, which means media uploads need to do
```js
media: {
  originalname: file.name,
  buffer: Buffer.from(await file.arrayBuffer(), 'binary'),
},
```
instead of just
```js
media: file
```

**Comment by tonyspiro** [comment]
Thank you @KaelWD. This is noted in [the docs](https://www.cosmicjs.com/docs/api/media#create-media). Do you have a recommended implementation for this? Feel free to make a PR.

**Comment by KaelWD** [comment]
Currently I'm just using patch-package to remove the form-data import, node has had FormData built in since v18.

**Comment by tonyspiro** [comment]
Closing this as it needs more consideration.
